version: '3.8'
services:
  home-library:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: home-library-c
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - 4000:4000

  postgres:
    container_name: postgres_db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres-db:/data/postgres
    ports:
      - 5432:5432

volumes:
  postgres-db:
    driver: local
