version: '3.8'
services:
  home-library:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    container_name: home-library-c
    image: home-lib:v1
    command: npm run start:dev
    restart: always
    volumes:
      - ./src:/app/src
    env_file:
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - postgres-db
    networks:
      - api

  postgres-db:
    container_name: postgres-db
    image: postgres:15-alpine
    restart: always
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - api

  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
    name: db_data
    driver: local

networks:
  api:
    driver: bridge
